# Generated by Django 5.2.2 on 2025-06-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
