# Generated by Django 5.2.2 on 2025-06-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
    ]
