# Generated by Django 5.2.2 on 2025-06-10 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestiones', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('examen', 'Examen'), ('tarea', 'Tarea'), ('participacion', 'Participación'), ('otro', 'Otro')], max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestiones.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='materias.materia')),
            ],
        ),
    ]
