# Generated by Django 5.2.2 on 2025-06-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='dimension',
            field=models.CharField(choices=[('ser', 'Ser'), ('saber', 'Saber'), ('hacer', 'Hacer'), ('decidir', 'Decidir')], default='saber', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='trimestre',
            field=models.IntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')], default=1),
        ),
    ]
