# Generated by Django 5.2.2 on 2025-06-10 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestiones', '0001_initial'),
        ('materias', '0001_initial'),
        ('usuarios', '0002_director_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='usuarios.alumno')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestiones.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='materias.materia')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('alumno', 'materia', 'gestion', 'fecha')},
            },
        ),
    ]
