# Generated by Django 5.2.2 on 2025-06-13 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
        ('cursos', '0002_curso_nivel_curso_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
