# Generated by Django 5.2.2 on 2025-06-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('Inicial', 'Inicial'), ('Primario', 'Primario'), ('Secundario', 'Secundario')], max_length=20)),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20)),
                ('gestion', models.IntegerField()),
            ],
        ),
    ]
