# Generated by Django 5.2.2 on 2025-06-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_nivel_curso_turno'),
        ('usuarios', '0002_director_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='cursos.curso'),
        ),
    ]
