# Generated by Django 5.2.2 on 2025-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
