# Generated by Django 5.2.2 on 2025-06-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_alumno_codigo_padre_alumno_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='usuarios.padre'),
        ),
    ]
