# Generated by Django 5.2.2 on 2025-06-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_alumno_codigo'),
        ('usuarios', '0006_alter_alumno_padre'),
    ]

    operations = [
    ]
