# Generated by Django 5.2.2 on 2025-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_20250612_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('director', 'Director'), ('padre', 'Padre')], default='alumno', max_length=20, verbose_name='Rol del Usuario'),
        ),
    ]
