# Generated by Django 5.2.2 on 2025-06-10 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('usuarios', '0002_director_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_evaluacion', to='usuarios.alumno')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='evaluaciones.evaluacion')),
            ],
            options={
                'unique_together': {('evaluacion', 'alumno')},
            },
        ),
    ]
